### ISSUE TITLE
building on debian gnu/linux, sid failed for me

### ISSUE THREAD

**Issue by alexmyczko** [phkaeser/wlmaker#3]
```
[ 45%] Building C object src/CMakeFiles/wlmaker.dir/button.c.o
cd /var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/obj-x86_64-linux-gnu/src && /usr/bin/cc -DHAVE_CAIRO -DWLMAKER_ICON_DATA_DIR=\"/usr/share/icons/wlmaker\" -DWLMAKER_SOURCE_DIR=\"/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds\" -I/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/obj-x86_64-linux-gnu/third_party/protocols -I/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/obj-x86_64-linux-gnu/protocols -I/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/submodules/libbase/.. -I/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/src/toolkit/.. -isystem /usr/include/cairo -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -g -O2 -ffile-prefix-map=/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu11 -Wall -Wextra -Werror -ggdb -DDEBUG -O0 -fmacro-prefix-map=/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds=. -I/usr/include -MD -MT src/CMakeFiles/wlmaker.dir/button.c.o -MF CMakeFiles/wlmaker.dir/button.c.o.d -o CMakeFiles/wlmaker.dir/button.c.o -c /var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/src/button.c
/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/src/button.c: In function ‘_button_enter’:
/var/www/debian/wlmaker/2/wlmaker-0.1+git20231230+ds/src/button.c:218:5: error: implicit declaration of function ‘wlr_xcursor_manager_set_cursor_image’; did you mean ‘wlr_xcursor_manager_get_xcursor’? [-Werror=implicit-function-declaration]
  218 |     wlr_xcursor_manager_set_cursor_image(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     wlr_xcursor_manager_get_xcursor
cc1: all warnings being treated as errors
```

is there an easy fix?

**Comment by phkaeser** [comment]
Hej Alex,

hm... I suspect it's because libwlroots is built from sid, and it's a
rather fast moving target (the API isn't defined as stable, and I recall
wlr_xcursor had some changes).

Due to that, I have defined and versioned the key dependencies of wlmaker
as git submodules:
https://github.com/phkaeser/wlmaker/blob/main/dependencies/CMakeLists.txt

# first time: update the submodules.
git submodule update --init --recursive --merge
cd dependencies
cmake -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/.local -B build
# build AND install into your ${HOME}/.local
(cd build && make)
cd ..

# For configuring & building wlmaker: We need to refer to these installed
packages.
export LD_LIBRARY_PATH="${HOME}/.local/lib/x86_64-linux-gnu"
export
PKG_CONFIG_PATH="${HOME}/.local/lib/x86_64-linux-gnu/pkgconfig/:${HOME}/.local/share/pkgconfig/"

cmake -B build/ -DCMAKE_INSTALL_PREFIX="${HOME}/.local"
(cd build && make)

That should build it.
Note: I don't think I had been very disciplined in declaring all library
dependencies => these are the packages I got installed for me:

apt-get install \
  foot \
  glslang-dev \
  glslang-tools \
  graphviz \
  libgbm-dev \
  libinput-dev \
  libudev-dev \
  libvulkan-dev \
  libxcb-composite0-dev \
  libxcb-dri3-dev \
  libxcb-ewmh-dev \
  libxcb-icccm4-dev \
  libxcb-present-dev \
  libxcb-render-util0-dev \
  libxcb-res0-dev \
  libxcb-xinput-dev \
  libxkbcommon-dev \
  meson \
  plantuml \
  xmlto \
  xsltproc

Let me know if that doesn't work. And: Yeah, the documentation should get
an update... sorry for that :)

yours,
Philipp

**Comment by probonopd** [comment]
What is `foot`? Doesn't seem to exist on Ubuntu focal?

**Comment by phkaeser** [comment]
Foot is a minimalistic Wayland terminal emulator:
https://packages.debian.org/bookworm/foot -- I'd expect it's available on
sid, too.  (I'm developing on bookworm)

Not required for building wlmaker. In version 0.1, the launchers are
hard-coded, and "foot" is the terminal emulator I used there.

**Comment by probonopd** [comment]
Looks like the package `wayland-protocols` also needs to be installed.

**Comment by phkaeser** [comment]
Thanks for flagging!

(Let me know if you find others, can't hurt to fix my list...)

**Comment by probonopd** [comment]
`libwlroots-dev doxygen`

Would you be interested in having automated builds using GitHub Actions?

**Comment by phkaeser** [comment]
libwlroots-dev should not be required, when built with proper settings from
the submodules.

doxygen: Argh, yes!

Yes, highly interested in having automated builds. Also would be happy to
have tests + doc targets ran as a presubmit.
Contributions most welcome :)

**Comment by probonopd** [comment]
On it.
Can you elaborate on "when built with proper settings from the submodules" please?

**Comment by phkaeser** [comment]
Basically the sequence from the first mail:
* Get the git submodules (the dependencies/ and submodules/ contents of
wlmaker).
* Build (& install) these first.
* then, configure & build wlmaker using these.
My hack so far is to export PKG_CONFIG_PATH and LD_LIBRARY_PATH. That's not
very clean, though... very happy to hear suggestions! :)



# first time: update the submodules.
git submodule update --init --recursive --merge
cd dependencies
cmake -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/.local -B build
# build AND install into your ${HOME}/.local
(cd build && make)
cd ..

# For configuring & building wlmaker: We need to refer to these installed
packages.
export LD_LIBRARY_PATH="${HOME}/.local/lib/x86_64-linux-gnu"
export
PKG_CONFIG_PATH="${HOME}/.local/lib/x86_64-linux-gnu/pkgconfig/:${HOME}/.local/share/pkgconfig/"

cmake -B build/ -DCMAKE_INSTALL_PREFIX="${HOME}/.local"
(cd build && make)

**Comment by probonopd** [comment]
WIP GitHub Actions workflow:
https://github.com/probonopd/wlmaker/blob/patch-1/.github/workflows/build_and_upload_artifact.yml

Running into:

```

Found pkg-config: /usr/bin/pkg-config (1.8.1)
Dependency wayland-server found: NO found 1.21.0 but need: '>=1.22'
Found CMake: /usr/bin/cmake (3.25.1)
Run-time dependency wayland-server found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-server

../../../../wlroots/meson.build:105:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.
```

Full log: https://github.com/probonopd/wlmaker/actions/runs/7366468282/job/20048756798

**Comment by phkaeser** [comment]
https://github.com/phkaeser/wlmaker/actions/workflows/build-for-linux.yml addresses the "building" aspect; although technically on ubuntu-latest, not on debian/sid.

Pending: Find a good means to publish it as a binary (eg. a flatpak?). Due to wlroots having significant API changes across versions, that will need to bundle some of the dependencies.

**Comment by phkaeser** [comment]
Filed #26 for that pending aspect, but will close here, since building should be fine now.

**Comment by alexmyczko** [comment]
i've been missing screenshots. instead of trying to build, could also just ask if you could provide screenshots? and are you aware of gsde and nextspace projects?

**Comment by alexmyczko** [comment]
now it builds... http://sid.ethz.ch/debian/wlmaker/3/

**Comment by alexmyczko** [comment]
I can move the mouse cursor!!!![image](https://github.com/phkaeser/wlmaker/assets/21078693/f419fc8c-62ca-4829-b2e7-ee6db227bb57)

**Comment by phkaeser** [comment]
😂😂 ... at least it's running!

Clicking the buttons *would* run an app, too... if they are installed. I'm afraid v0.1 is "experimental" proper, with the apps hard-configured in code.

Curious: Did you run it in a window (from X11 or another Wayland compositor)?

For a standalone session, it should use up all available output space, hence wondering.

**Comment by alexmyczko** [comment]
I have run it on http://bananas.debian.net a Debian GNU/Linux Apple laptop with M1, arm64. Using startx from console with .xsessionc conetent exec wlmaker
