### ISSUE TITLE
Implement --replace to easily try out wlmaker in an existing Wayland session

### ISSUE THREAD

**Issue by probonopd** [phkaeser/wlmaker#5]
It would be useful to have an easy(!) way to try out wlmaker, e.g., by a `--replace` argument to switch out whatever compositor is currently running with the launched wlmaker instance in an existing Wayland session.

**Comment by probonopd** [comment]
Apparently the following works (e.g, in Fedora KDE Live ISOs):

```
sudo systemctl stop display-manager.service
./appdir/usr/bin/wlmaker
```

**Comment by phkaeser** [comment]
Agree this be useful. I'm not sure this is well supported by Wayland, though => since the compositor is itself running the compositing service, there doesn't seem to be an easy way to "take over" compositing duties from another compositor.

(at least: libwlroots doesn't seem to offer that, and eg. sway or labwc as two of my references don't offer a `--replace` argument).

Workaround: Running `wlmaker` as a user-space will (should!) bring it up in window mode (in X11 and/or Wayland). 

Does that address the "trying out" need?

**Comment by phkaeser** [comment]
With #73 , documentation was added to run `wlmaker` in windowed mode, from a virtual terminal, or (for the brave) run it as session manager. I believe this addresses the purpose of trying it out, hence closing this issue.

@probonopd please re-open if this seems wrong and clarify what else is missing. Thank you!
